import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import { Oswald } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import { Inter } from "next/font/google";
import { Shrikhand } from "next/font/google";
import "./globals.css";
import SignupSuccessModal from "@/components/ui/signupSuccessModal";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-oswald",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-playfair",
});

export const shrikhand = Shrikhand({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-shrikhand",
});

export const metadata: Metadata = {
  title: "Barber Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${bebasNeue.variable} ${oswald.variable} ${playfair.variable} ${inter.variable} ${shrikhand.variable} antialiased bg-black`}
      >
        <section className="bg-default font-body">
          <SignupSuccessModal />
          {children}
        </section>
      </body>
    </html>
  );
}
